### ISSUE TITLE
Contacts View is Dead Leaf

### ISSUE THREAD

**Issue by G-Dooley** [GovTribe/bat-search#27]
When performing a search, a list of contacts is displayed in a container on the right. Selecting a contact, then provides the list of the associated contacts in the main window, with the contact selected underneath. Selecting the contact changes the UI to display contact information. There are two buttons ("X" and "Close"), pressing either does nothing.

It doesnt seem like there is anyway to navigate back to search results outside of refreshing the browser or pressing the back button (Which doesnt exist in an IFrame).

**Comment by natenash203** [comment]
Hey Gary - We pushed a fix this morning that I think addresses your issue. Let me know if you are still experiencing it.

**Comment by G-Dooley** [comment]
Still experiencing the issue.

**Comment by natenash203** [comment]
Hey Gary - No prob. Sent you an email asking if we could chat on the phone.
