### ISSUE TITLE
Allow for combining of facets. See comment for limiting approach

### ISSUE THREAD

**Issue by natenash203** [GovTribe/bat-search#34]
Allow one organizational facet to be combined with one lifecycle or type facet. 

Organizational facets are defined as:
Agency, Office, Person, Category

Lifecycle status facets:
Status, SetAside, GoodOrServices. 

Example User Story: I am interested in water purification contracts. I search then click on Dept of Army (org facet). After that I want to further refine search results by seeing contracts with a small biz set aside by clicking on the setAside facet (type facet)

**Comment by jhariani** [comment]
Users can now select any combination of facets.
